.Dd November 14, 2020
.Dt HTEEML 1
.Os
.Sh NAME
.Nm hteeml
.Nd capture a program's output as HTML
.Sh SYNOPSIS
.Nm
.Ar program
.Ar argument
.Op Ar ...
.Sh DESCRIPTION
Runs the given program, captures its stdout and sterr,
and combines them into an HTML document
where stderr is marked up red.
.Pp
ANSI escape sequences are not interpreted.
For that, see
.Lk https://github.com/theZiz/aha aha .
.Sh AUTHORS
.An Sijmen J. Mulder
.Aq Mt ik@sjmulder.nl
